spring.application.name=Rattrapage-prog3

# L'application doit repondre sur le port 8080
server.port=8080

spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
